### ISSUE TITLE
Append to log stops working if log is used in between

### ISSUE THREAD

**Issue by MichaelClerx** [myokit/myokit#410]
```
#!/usr/bin/env python3
import myokit
import matplotlib.pyplot as plt

m, p, _ = myokit.load('example')
s = myokit.Simulation(m, p)

d = s.run(100)
d = s.run(100, log=d)

s = myokit.Simulation(m, p)

d = s.run(100)

plt.figure()
plt.plot(d.time(), d['membrane.V'])

d = s.run(100, log=d)
```

Leads to

```
Traceback (most recent call last):
  File "./log_append.py", line 18, in <module>
    d = s.run(100, log=d)
  File "/home/michael/dev/myokit/myokit/_sim/cvodesim.py", line 277, in run
    msg)
  File "/home/michael/dev/myokit/myokit/_sim/cvodesim.py", line 384, in _run
    t = self._sim.sim_step()
Exception: Call to append() failed on logging list.
```

So it works the first time, but not if we do something in between

**Comment by MichaelClerx** [comment]
This looks to be a matplotlib specific thing, accessing in other ways doesn't change anything. Have raised an issue here: https://github.com/matplotlib/matplotlib/issues/16935

Doesn't seem to happen on python 2 with matplotlib 2.2.5, but does happen on python 3 with matplotlib 3.0.3

**Comment by MichaelClerx** [comment]
```
#!/usr/bin/env python3
import myokit
import numpy as np

m,p,_ = myokit.load('example')
s = myokit.Simulation(m,p)

d = s.run(100)
x = np.array(d['membrane.V'], copy=False)
d = s.run(100, log=d)
```
This is a matplotlib-free way of recreating this issue:

**Comment by MichaelClerx** [comment]
The example runs without errors in matplotlib 3.6.3 !

**Comment by MichaelClerx** [comment]
Fails in CI on 3.5.3
