### ISSUE TITLE
Module not found error on 1.31.0 on Win10 Python 3.8

### ISSUE THREAD

**Issue by MichaelClerx** [myokit/myokit#640]
```
[11:10:25] Loading Myokit IDE
[11:10:25] Opened C:\Users\user\Downloads\model.mmt
[11:10:31] Running embedded script.
[11:10:36] An error has occurred
[11:10:36] Traceback (most recent call last):
 File "c:\users\user\miniconda3\lib\site-packages\myokit\gui\ide.py", line 938, in action_run
   myokit.run(
 File "c:\users\user\miniconda3\lib\site-packages\myokit\_aux.py", line 1134, in run
   r.run()
 File "c:\users\user\miniconda3\lib\site-packages\myokit\_aux.py", line 1125, in run
   myokit._exec(self.script, environment)
 File "c:\users\user\miniconda3\lib\site-packages\myokit\_exec_new.py", line 15, in _exec
   exec(script, globals, locals)
 File "<string>", line 8, in <module>
 File "c:\users\user\miniconda3\lib\site-packages\myokit\_sim\cvodesim.py", line 150, in __init__
   self._sim = self._compile(module_name, fname, args, libs, libd, incd)
 File "c:\users\user\miniconda3\lib\site-packages\myokit\_sim\__init__.py", line 210, in _compile
   return load_module(name, d_build)
 File "c:\users\user\miniconda3\lib\site-packages\myokit\_sim\__init__.py", line 54, in load_module
   module = importlib.util.module_from_spec(spec)
 File "<frozen importlib._bootstrap>", line 556, in module_from_spec
 File "<frozen importlib._bootstrap_external>", line 1101, in create_module
 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing myokit_sim_1_8341692155779361965: The specified module could not be found.
```

**Comment by MichaelClerx** [comment]
Other reports say it works?

```
== System information ==
Myokit: 1.31.0
Python: 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]OS: Windows (win32, nt)

== Python requirements ==
NumPy: 1.17.2
SciPy: 1.3.1
Matplotlib: 3.1.1
ConfigParser: OK
Setuptools: 41.0.1

== Python extras ==
SymPy: 1.4
CMAES: 2.7.0
MoviePy: Not found

== GUI ==
PyQt5: 5.13.1
  Sip: OK
PyQt4: Not found
PySide: Not found
PySide2: Not found

== Development tools ==
Sphinx: Not found
Flake8: Not found

== Simulation tools ==
Compiler: Microsoft Visual Studio 15.0 (2017) - 192328106
Sundials: 2.7.0
OpenCL: No OpenCL support detected.
```

**Comment by MichaelClerx** [comment]
Different report

```
(mc) C:\Users\uczmh2\Desktop\mc>python -m myokit run example
WARNING:myokit._config:Sundials version not set in myokit.ini. Continuing with detected version (20700). For a tiny performance boost, please set this version in C:\Users\uczmh2\.config\myokit\myokit.ini
Reading model from example
File loaded in 0.028229300000000457 seconds
Model read successfully
0 validation warning(s) given
Using embedded script
------------------------------------------------------------
  1 import myokit
  2
  3 # Load model and protocol
  4 print('Loading model and protocol...')
  5 m = get_model()
  6 p = get_protocol()
  7 print('Creating simulation object...')
  8 s = myokit.Simulation(m, p)
  9 print('Running simulation...')
 10 s.pre(1000)
 11 d = s.run(1000)
 12
 13 # Show results
 14 print('Loading matplotlib...')
 15 import matplotlib.pyplot as plt
 16 plt.figure()
 17 plt.plot(d['engine.time'], d['membrane.V'])
 18 plt.show()
 19
------------------------------------------------------------
Loading model and protocol...
Creating simulation object...
Traceback (most recent call last):
  File "C:\Program Files (x86)\python\lib\distutils\_msvccompiler.py", line 520, in link
    self.spawn([self.linker] + ld_args)
  File "C:\Program Files (x86)\python\lib\distutils\_msvccompiler.py", line 543, in spawn
    return super().spawn(cmd)
  File "C:\Program Files (x86)\python\lib\distutils\ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\Program Files (x86)\python\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\Program Files (x86)\python\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120During handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "C:\Program Files (x86)\python\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files (x86)\python\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Program Files (x86)\python\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\uczmh2\Desktop\mc\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "C:\Program Files (x86)\python\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Program Files (x86)\python\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Program Files (x86)\python\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\uczmh2\Desktop\mc\lib\site-packages\setuptools\command\build_ext.py", line 205, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Program Files (x86)\python\lib\distutils\command\build_ext.py", line 559, in build_extension
    target_lang=language)
  File "C:\Program Files (x86)\python\lib\distutils\ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "C:\Program Files (x86)\python\lib\distutils\_msvccompiler.py", line 523, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120

During handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "C:\Users\uczmh2\Desktop\mc\lib\site-packages\myokit\_sim\__init__.py", line 196, in _compile
    str('--inplace'),
  File "C:\Users\uczmh2\Desktop\mc\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Program Files (x86)\python\lib\distutils\core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120During handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "C:\Program Files (x86)\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\uczmh2\Desktop\mc\lib\site-packages\myokit\__main__.py", line 2074, in <module>
    main()
  File "C:\Users\uczmh2\Desktop\mc\lib\site-packages\myokit\__main__.py", line 86, in main
    func(**args)
  File "C:\Users\uczmh2\Desktop\mc\lib\site-packages\myokit\__main__.py", line 1084, in run
    myokit.run(model, protocol, script)
  File "C:\Users\uczmh2\Desktop\mc\lib\site-packages\myokit\_aux.py", line 1134, in run
    r.run()
  File "C:\Users\uczmh2\Desktop\mc\lib\site-packages\myokit\_aux.py", line 1125, in run
    myokit._exec(self.script, environment)
  File "C:\Users\uczmh2\Desktop\mc\lib\site-packages\myokit\_exec_new.py", line 15, in _exec
    exec(script, globals, locals)
  File "<string>", line 9, in <module>
  File "C:\Users\uczmh2\Desktop\mc\lib\site-packages\myokit\_sim\cvodesim.py", line 150, in __init__
    self._sim = self._compile(module_name, fname, args, libs, libd, incd)
  File "C:\Users\uczmh2\Desktop\mc\lib\site-packages\myokit\_sim\__init__.py", line 207, in _compile
    raise myokit.CompilationError('\n'.join(t))
myokit._err.CompilationError: Unable to compile.
Error message:
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120
Error traceback
Traceback (most recent call last):
  File "C:\Program Files (x86)\python\lib\distutils\_msvccompiler.py", line 520, in link
    self.spawn([self.linker] + ld_args)
  File "C:\Program Files (x86)\python\lib\distutils\_msvccompiler.py", line 543, in spawn
    return super().spawn(cmd)
  File "C:\Program Files (x86)\python\lib\distutils\ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\Program Files (x86)\python\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\Program Files (x86)\python\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120During handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "C:\Program Files (x86)\python\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files (x86)\python\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Program Files (x86)\python\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\uczmh2\Desktop\mc\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "C:\Program Files (x86)\python\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Program Files (x86)\python\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Program Files (x86)\python\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\uczmh2\Desktop\mc\lib\site-packages\setuptools\command\build_ext.py", line 205, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Program Files (x86)\python\lib\distutils\command\build_ext.py", line 559, in build_extension
    target_lang=language)
  File "C:\Program Files (x86)\python\lib\distutils\ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "C:\Program Files (x86)\python\lib\distutils\_msvccompiler.py", line 523, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120During handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "C:\Users\uczmh2\Desktop\mc\lib\site-packages\myokit\_sim\__init__.py", line 196, in _compile
    str('--inplace'),
  File "C:\Users\uczmh2\Desktop\mc\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Program Files (x86)\python\lib\distutils\core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120Compiler output:
    running build_ext
    building 'myokit_sim_1_722045697' extension
    creating build
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    creating build\temp.win32-3.7\Release\Users
    creating build\temp.win32-3.7\Release\Users\uczmh2
    creating build\temp.win32-3.7\Release\Users\uczmh2\AppData
    creating build\temp.win32-3.7\Release\Users\uczmh2\AppData\Local
    creating build\temp.win32-3.7\Release\Users\uczmh2\AppData\Local\Temp
    creating build\temp.win32-3.7\Release\Users\uczmh2\AppData\Local\Temp\tmpkhrkdcw5myokit
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\uczmh2\Desktop\mc\lib\site-packages\myokit\_bin\sundials-win-vs\include -IC:\Users\uczmh2\Desktop\mc\lib\site-packages\myokit\_sim -IC:\Users\uczmh2\Desktop\mc\lib\site-packages\myokit\_sim -IC:\Users\uczmh2\Desktop\mc\include "-IC:\Program Files (x86)\python\include" "-IC:\Program Files (x86)\python\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /TcC:\Users\uczmh2\AppData\Local\Temp\tmpkhrkdcw5myokit\source.c /Fobuild\temp.win32-3.7\Release\Users\uczmh2\AppData\Local\Temp\tmpkhrkdcw5myokit\source.obj
    source.c
    creating C:\Users\uczmh2\AppData\Local\Temp\tmpkhrkdcw5myokit\build\build\lib.win32-3.7
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x86\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\uczmh2\Desktop\mc\lib\site-packages\myokit\_bin\sundials-win-vs\lib /LIBPATH:C:\Users\uczmh2\Desktop\mc\libs "/LIBPATH:C:\Program Files (x86)\python\libs" "/LIBPATH:C:\Program Files (x86)\python" /LIBPATH:C:\Users\uczmh2\Desktop\mc\PCbuild\win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\ATLMFC\lib\x86" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\lib\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x86" sundials_cvode.lib sundials_nvecserial.lib /EXPORT:PyInit_myokit_sim_1_722045697 build\temp.win32-3.7\Release\Users\uczmh2\AppData\Local\Temp\tmpkhrkdcw5myokit\source.obj /OUT:build\lib.win32-3.7\myokit_sim_1_722045697.cp37-win32.pyd /IMPLIB:build\temp.win32-3.7\Release\Users\uczmh2\AppData\Local\Temp\tmpkhrkdcw5myokit\myokit_sim_1_722045697.cp37-win32.lib
       Creating library build\temp.win32-3.7\Release\Users\uczmh2\AppData\Local\Temp\tmpkhrkdcw5myokit\myokit_sim_1_722045697.cp37-win32.lib and object build\temp.win32-3.7\Release\Users\uczmh2\AppData\Local\Temp\tmpkhrkdcw5myokit\myokit_sim_1_722045697.cp37-win32.exp
    source.obj : error LNK2001: unresolved external symbol __imp__CVodeSetMaxStep
    source.obj : error LNK2001: unresolved external symbol __imp__CVDense
    source.obj : error LNK2001: unresolved external symbol __imp__CVodeReInit
    source.obj : error LNK2001: unresolved external symbol __imp__CVodeSetMinStep
    source.obj : error LNK2001: unresolved external symbol __imp__CVodeCreate
    source.obj : error LNK2001: unresolved external symbol __imp__CVode
    source.obj : error LNK2001: unresolved external symbol __imp__N_VNew_Serial
    source.obj : error LNK2001: unresolved external symbol __imp__CVodeSStolerances
    source.obj : error LNK2001: unresolved external symbol __imp__N_VDestroy_Serial
    source.obj : error LNK2001: unresolved external symbol __imp__CVodeFree
    source.obj : error LNK2001: unresolved external symbol __imp__CVodeGetDky
    source.obj : error LNK2001: unresolved external symbol __imp__CVodeRootInit
    source.obj : error LNK2001: unresolved external symbol __imp__CVodeGetRootInfo
    source.obj : error LNK2001: unresolved external symbol __imp__CVodeInit
    build\lib.win32-3.7\myokit_sim_1_722045697.cp37-win32.pyd : fatal error LNK1120: 14 unresolved externals
```

**Comment by MichaelClerx** [comment]
But that was fixed when 64 bit python was installed!

**Comment by MichaelClerx** [comment]
![image003](https://user-images.githubusercontent.com/517644/101610667-76a70380-3a00-11eb-8606-5cf03b6ea423.png)

Another one

**Comment by MichaelClerx** [comment]
Can recreate on a fresh win 10 with miniconda and latest myokit

```

(base) C:\Users\michael>python -m myokit run example
Reading model from example
File loaded in 0.022707299999999986 seconds
Model read successfully
0 validation warning(s) given
Using embedded script
------------------------------------------------------------
  1 import myokit
  2
  3 # Load model and protocol
  4 print('Loading model and protocol...')
  5 m = get_model()
  6 p = get_protocol()
  7 print('Creating simulation object...')
  8 s = myokit.Simulation(m, p)
  9 print('Running simulation...')
 10 s.pre(1000)
 11 d = s.run(1000)
 12
 13 # Show results
 14 print('Loading matplotlib...')
 15 import matplotlib.pyplot as plt
 16 plt.figure()
 17 plt.plot(d['engine.time'], d['membrane.V'])
 18 plt.show()
 19
------------------------------------------------------------
Loading model and protocol...
Creating simulation object...
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\lib\site-packages\myokit\__main__.py", line 2074, in <module>
    main()
  File "C:\ProgramData\Miniconda3\lib\site-packages\myokit\__main__.py", line 86, in main
    func(**args)
  File "C:\ProgramData\Miniconda3\lib\site-packages\myokit\__main__.py", line 1084, in run
    myokit.run(model, protocol, script)
  File "C:\ProgramData\Miniconda3\lib\site-packages\myokit\_aux.py", line 1134, in run
    r.run()
  File "C:\ProgramData\Miniconda3\lib\site-packages\myokit\_aux.py", line 1125, in run
    myokit._exec(self.script, environment)
  File "C:\ProgramData\Miniconda3\lib\site-packages\myokit\_exec_new.py", line 15, in _exec
    exec(script, globals, locals)
  File "<string>", line 9, in <module>
  File "C:\ProgramData\Miniconda3\lib\site-packages\myokit\_sim\cvodesim.py", line 150, in __init__
    self._sim = self._compile(module_name, fname, args, libs, libd, incd)
  File "C:\ProgramData\Miniconda3\lib\site-packages\myokit\_sim\__init__.py", line 210, in _compile
    return load_module(name, d_build)
  File "C:\ProgramData\Miniconda3\lib\site-packages\myokit\_sim\__init__.py", line 54, in load_module
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing myokit_sim_1_3196370879397037565: The specified module could not be found.
```

**Comment by MichaelClerx** [comment]
Could be a 3.8 issue rather than myokit version specific:

https://docs.python.org/3/whatsnew/3.8.html#changes-in-the-python-api

> DLL dependencies for extension modules and DLLs loaded with ctypes on Windows are now resolved more securely. Only the system paths, the directory containing the DLL or PYD file, and directories added with add_dll_directory() are searched for load-time dependencies. Specifically, PATH and the current working directory are no longer used, and modifications to these will no longer have any effect on normal DLL resolution. If your application relies on these mechanisms, you should check for add_dll_directory() and if it exists, use it to add your DLLs directory while loading your library. Note that Windows 7 users will need to ensure that Windows Update KB2533623 has been installed (this is also verified by the installer). (Contributed by Steve Dower in bpo-36085.)

**Comment by MichaelClerx** [comment]
Nope, that was already addressed here: https://github.com/MichaelClerx/myokit/issues/546

Now reading this: https://vxlabs.com/2017/12/06/how-to-debug-pyinOK That bit was fixed already staller-dll-pyd-load-failed-issues-on-windows/

**Comment by MichaelClerx** [comment]
That helped. Ctypes couldn't find the generated module (or possibly the DLLs it needs, not sure!). Worked when added to sys.path again (even though that should not work in 3.8??)

**Comment by MichaelClerx** [comment]
Closed in #679

**Comment by MichaelClerx** [comment]
```
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\myokit.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\myokit\__main__.py", line 86, in main
    func(**args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\myokit\__main__.py", line 1082, in run
    myokit.run(model, protocol, script)
  File "C:\ProgramData\Anaconda3\lib\site-packages\myokit\_aux.py", line 523, in run
    r.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\myokit\_aux.py", line 514, in run
    myokit._exec(self.script, environment)
  File "C:\ProgramData\Anaconda3\lib\site-packages\myokit\_exec_new.py", line 15, in _exec
    exec(script, globals, locals)
  File "<string>", line 9, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\myokit\_sim\cvodessim.py", line 152, in __init__
    self._create_simulation(cmodel.code)
  File "C:\ProgramData\Anaconda3\lib\site-packages\myokit\_sim\cvodessim.py", line 221, in _create_simulation
    self._sim = self._compile(module_name, fname, args, libs, libd, incd)
  File "C:\ProgramData\Anaconda3\lib\site-packages\myokit\_sim\__init__.py", line 216, in _compile
    return load_module(name, d_build)
  File "C:\ProgramData\Anaconda3\lib\site-packages\myokit\_sim\__init__.py", line 56, in load_module
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: DLL load failed while importing myokit_sim_1_2699684234790732738: The specified module could not be found.
```

**Comment by MichaelClerx** [comment]
Unit tests work in every version: https://github.com/MichaelClerx/myokit/runs/4619381777?check_suite_focus=true
Maybe need to try with miniconda to recreate?

**Comment by MichaelClerx** [comment]
No recent reports. All tests work...
