### ISSUE TITLE
Exception during error handling in cvodes sim

### ISSUE THREAD

**Issue by MichaelClerx** [myokit/myokit#911]
```   
Traceback (most recent call last):                                                                      
  File "./fit.py", line 211, in <module>                                                                
    unchanged)                                                                                          
  File "/home/michael/dev/nyfit/methods/fitio.py", line 404, in fit
    p, s = opt.run()                                          
  File "/home/michael/dev/pints/pints/_optimisers/__init__.py", line 637, in run
    fs = evaluator.evaluate(xs)                                 
  File "/home/michael/dev/pints/pints/_evaluation.py", line 119, in evaluate   
    return self._evaluate(positions)                                           
  File "/home/michael/dev/pints/pints/_evaluation.py", line 365, in _evaluate  
    + '\nException in subprocess')                                                                      
Exception: Exception in subprocess:                                 
Traceback (most recent call last):                                                                      
  File "/home/michael/dev/myokit/myokit/_sim/cvodessim.py", line 779, in _run
    t = self._sim.sim_step()                                                                            
ArithmeticError: Function CVode() failed with flag -4 CV_CONV_FAILURE: Convergence test failures occurre
d too many times during one internal time step or minimum step size was reached.                        
                                                                
During handling of the above exception, another exception occurred:                                     
                                                                                                        
Traceback (most recent call last):                                                           
  File "/home/michael/dev/pints/pints/_evaluation.py", line 556, in run                                 
    f = self._function(x, *self._args)                                          
  File "./fit.py", line 132, in __call__                                                                
    return self._e(parameters)
  File "/home/michael/dev/pints/pints/_error_measures.py", line 102, in __call__
    return np.sum(((np.sum((self._problem.evaluate(x) - self._values)**2,
  File "/home/michael/dev/pints/pints/_core.py", line 152, in evaluate
    y = np.asarray(self._model.simulate(parameters, self._times))
  File "/home/michael/dev/nyfit/methods/_models.py", line 963, in simulate
    return self._simulate(parameters)[0]
  File "/home/michael/dev/nyfit/methods/_models.py", line 909, in _simulate
    progress=_Timeout(self._max_evaluation_time),
  File "/home/michael/dev/myokit/myokit/_sim/cvodessim.py", line 616, in run
    apd_variable, apd_threshold, progress, msg)
  File "/home/michael/dev/myokit/myokit/_sim/cvodessim.py", line 811, in _run
    self._model.evaluate_derivatives(state)
  File "/home/michael/dev/myokit/myokit/_model_api.py", line 1386, in evaluate_derivatives
    values[eq.lhs] = eq.rhs.eval(values, precision=precision)
  File "/home/michael/dev/myokit/myokit/_expressions.py", line 378, in eval
    v = float(v)
TypeError: can't convert complex to float
```

From these lines:
```
                # Check if state derivatives can be evaluated in Python, if
                # not, add the error to the error message.
                try:
                    self._model.evaluate_derivatives(state)
                except myokit.NumericalError as en:
                    txt.append(str(en))

                # Raise numerical simulation error
                raise myokit.SimulationError('\n'.join(txt))
```

Here `self._model.evaluate_derivatives(state)` produces an unexpected TypeError, which is not converted to nice simulation output

**Comment by MichaelClerx** [comment]
Should maybe just catch any old exception there, at the risk of masking errors?
Should be OK, as evaluate_derivatives has unit tests?
